name = "support-agent"
main = "src/dev/test.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "support-knowledge"

[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]

[queues]
producers = [
  { binding = "MESSAGE_QUEUE", queue = "support-messages" }
]
consumers = [
  { queue = "support-messages" }
]

[[workflows]]
name = "knowledge-workflow"
binding = "KNOWLEDGE_WORKFLOW"
class_name = "KnowledgeWorkflow"
entrypoint = "src/workflows/knowledge.ts"
